# Config file for GitHub Pages site


title: [Jonathan S Celaya]
description: [Welcome to my personal site!]

# Theme
#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme

theme: jekyll-theme-leap-day
